#!/bin/bash

echo -e "\n🎉 HACS repository validator action summary 🎉\n"

grep -v '^ *#' < "$1/result" | while IFS= read -r line
do
  echo "$line"
done

if [ -f "$1/error" ]; then
  echo "::error::One or more checks failed!"
  exit 1
else
  printf "✅ All checks completed 🎉\n"
fi