#!/bin/bash

EMOJI_CHECK="✅"
EMOJI_RED_X="❌"
EMOJI_WHITE_CIRCLE="⚪"

function repoInfo () {
  info=$(jq ."$1" -r "$GITHUB_ACTION_PATH/data/info") > /dev/null
  echo "$info"
}

function checkInit () {
  echo "::group::$GROUP"
  echo "More info: $URL"
}

function checkComplete () {
  echo "::endgroup::"
}

function checkSuccess () {
  echo "$EMOJI_CHECK $1" >> "$GITHUB_ACTION_PATH/result"
}

function checkNeutral () {
  echo "$EMOJI_WHITE_CIRCLE $1 (more-info: $URL )" >> "$GITHUB_ACTION_PATH/result"
}

function checkError () {
  echo "::error::$1"
  msg="$1 (more-info: $URL )"
  echo "$EMOJI_RED_X $msg" >> "$GITHUB_ACTION_PATH/result"
  touch "$GITHUB_ACTION_PATH/error"
}

function checkWarning () {
  echo "::warning::$1"
}

function setOutput () {
  echo "::set-output name=$1::$2"
}

function checkRun () {
  echo "No checkRun function for $GROUP"
}

function checkCondition () {
  return 0
}

function checkIgnored () {
  ignore=$(cat "$GITHUB_ACTION_PATH/data/ignore")
  if [[ "$ignore" =~ $GROUP ]]; then
    return 1
  fi
}

function checkExecute () {
  if checkIgnored ;then
    if checkCondition ;then
      checkInit
      checkRun
      checkComplete
    fi
  else
    echo "$EMOJI_WHITE_CIRCLE Ignored check: $GROUP" >> "$GITHUB_ACTION_PATH/result"
  fi
}