#!/bin/bash

function repoInfo () {
  return $(jq .$1 -r "$GITHUB_ACTION_PATH/data/info") > /dev/null
}

function checkInit () {
  echo "::group::$GROUP"
  echo "More info: $URL"
}

function checkComplete () {
  echo "::endgroup::"
}

function checkSuccess () {
  echo "✅ $1" >> "$GITHUB_ACTION_PATH/result"
}

function checkNeutral () {
  echo "⚪ $1 (more-info: $URL )" >> "$GITHUB_ACTION_PATH/result"
}

function checkError () {
  echo "::error::$1"
  msg="$1 (more-info: $URL )"
  echo "❌ $msg" >> "$GITHUB_ACTION_PATH/result"
  touch "$GITHUB_ACTION_PATH/error"
}

function checkWarning () {
  echo "::warning::$1"
}

function setOutput () {
  echo "::set-output name=$1::$2"
}

function checkRun () {
  echo "No checkRun function for $GROUP"
}

function checkCondition () {
  return 0
}

function checkIgnored () {
  ignore=$(cat "$GITHUB_ACTION_PATH/data/ignore")
  if [[ "$ignore" =~ "$GROUP" ]]; then
    return 1
  fi
}

function checkExecute () {
  checkIgnored
  if [ "$?" == 0 ];then
    checkCondition
    if [ "$?" == 0 ];then
      checkInit
      checkRun
      checkComplete
    fi
  else
    echo "⚪ Ignored check: $GROUP" >> "$GITHUB_ACTION_PATH/result"
  fi
}