#!/bin/bash

declare -a checks=(
  archived
  manifest
  hacsjson
  description
  brands
  topics
  issues
  day
  fork
  information
  #requirements
  images
)

for check in ${checks[@]}; do
  source "$GITHUB_ACTION_PATH/common"
  source "$GITHUB_ACTION_PATH/checks/$check"
  checkExecute
done