#!/bin/bash

declare -a checks=(
  archived
  manifest
  description
  brands
  topics
  issues
)

for check in $({checks[@]}); do
  source "$GITHUB_ACTION_PATH/common"
  source "$GITHUB_ACTION_PATH/checks/$check"
  checkExecute
done