#!/bin/bash
URL="https://hacs.xyz/docs/publish/include#check-images"
GROUP="images"

function checkCondition () {
  category=$(cat "$GITHUB_ACTION_PATH"/data/category)
  if [ "$category" == "plugin" ] || [ "$category" == "theme" ]; then
    return 0
  fi
  return 1
}

function checkRun () {
  images=$(python3 "$GITHUB_ACTION_PATH"/helpers/findimages.py)
  if [ -n "${images}" ]; then
    echo "${images}"
    checkSuccess "Information file has images"
  else
    checkError "There should be images to show the user what they get"
  fi
}
