#!/bin/bash
URL="https://hacs.xyz/docs/publish/include#check-manifest"
GROUP="manifest"

declare -a requiredKeys=(
  issue_tracker
  domain
  documentation
  codeowners
)

function checkCondition () {
  category=$(cat "$GITHUB_ACTION_PATH"/data/category)
  if [ "$category" != "integration" ]; then
    return 1
  fi
}

function checkRun () {
  manifest=$(find "$(cat $GITHUB_ACTION_PATH/data/path)" -name manifest.json)
  if [ ! -f "$manifest" ]; then
    checkError "manifest.json file not found"
    exit 1
  else
    checkSuccess "manifest.json file exist"
    cat "$manifest" | jq .
    for key in ${requiredKeys[@]}; do
      if [ "$(jq --arg entry $key '.[$entry]' -r "$manifest")" == "null" ]; then
        checkError "manifest.json file missing key $key"
        exit 1
      fi
    done
    checkSuccess "All required keys are present in manifest.json"
  fi
}
