#!/bin/bash
source "$GITHUB_ACTION_PATH/checks/common"

URL="https://hacs.xyz/docs/publish/include#check-manifest"
GROUP="manifest"

function checkRun () {
  manifest=$(find "$1" -name manifest.json)
  if [ ! -f "$manifest" ]; then
    checkError "manifest.json file not found" $URL
    exit 1
  else
    setOutput "path" "$manifest"
    cat "$manifest" | jq .
    for key in "issue_tracker domain documentation codeowners"; do
      if [ -z "$(jq --arg entry "$key" '.[$entry]' -r "$manifest")" ]; then
        checkError "manifest.json file missing key $key $moreinfo" $URL
        exit 1
      fi
    done
  fi
}

checkInit "$GROUP" "$URL"
checkRun $*
checkComplete