#!/bin/bash
URL="https://hacs.xyz/docs/publish/include#check-requirements"
GROUP="requirements"

function checkCondition () {
  category=$(cat "$GITHUB_ACTION_PATH"/data/category)
  if [ "$category" == "integration" ]; then
    requirements=$(jq -r '. | select(.requirements != null) | .requirements[]' "$GITHUB_ACTION_PATH/data/manifest.json") > /dev/null
    if [ -n "$requirements" ]; then
      return 0
    fi
  fi
  return 1
}


function checkRun () {
  repoPath=$(cat "$GITHUB_ACTION_PATH"/data/path)
  mkdir -p "$repoPath/requirements"
  git clone --quiet --depth 1 https://github.com/home-assistant/wheels-custom-integrations.git "$repoPath/wheels-custom-integrations"  > /dev/null
  cd "$repoPath/wheels-custom-integrations"
  jq -r .requirements "$GITHUB_ACTION_PATH/data/manifest.json" > "$repoPath/wheels-custom-integrations/validate_requirements/files.json"
  cp  "$GITHUB_ACTION_PATH/helpers/requirements/__init__.py" "$repoPath/wheels-custom-integrations/validate_requirements"
  cp  "$GITHUB_ACTION_PATH/helpers/requirements/run.sh" "$repoPath/wheels-custom-integrations/validate_requirements"
  cp  "$GITHUB_ACTION_PATH/helpers/requirements/additional_requirements.py" "$repoPath/wheels-custom-integrations"
  cp  "$GITHUB_ACTION_PATH/helpers/requirements/additional_requirements.json" "$repoPath/wheels-custom-integrations"
  python3 "$repoPath/wheels-custom-integrations/additional_requirements.py"
  docker build -t validate -f validate_requirements/Dockerfile .
  set +e
  docker run --rm validate
  requirements="$?"
  set -e
  if [ "${requirements}" == 0 ]; then
    checkSuccess "Requirements validation"
  else
    checkError "Requirements validation"
  fi
}
