#!/bin/bash
URL="https://hacs.xyz/docs/publish/include#check-requirements"
GROUP="requirements"

function checkCondition () {
  category=$(cat "$GITHUB_ACTION_PATH"/data/category)
  if [ "$category" == "integration" ]; then
    requirements=$(jq -r '. | select(.requirements != null) | .requirements[]' "$GITHUB_ACTION_PATH/data/manifest.json") > /dev/null
    if [ -n "$requirements" ]; then
      return 0
    fi
  fi
  return 1
}


function checkRun () {
  repoPath=$(cat "$GITHUB_ACTION_PATH"/data/path)
  mkdir -p "$repoPath/requirements"
  wget -q -O "$GITHUB_ACTION_PATH/helpers/requirements/validate_requirements.py" \
    https://raw.githubusercontent.com/home-assistant/wheels-custom-integrations/master/scripts/validate_requirements.py
  cd "$GITHUB_ACTION_PATH/helpers/requirements"
  jq -r .requirements "$GITHUB_ACTION_PATH/data/manifest.json" > ./requirements.json
  jq . ./requirements.json
  docker build . -t homeassistant/home-assistant:beta
  set +e
  docker run homeassistant/home-assistant:beta
  requirements="$?"
  set -e
  if [ "${requirements}" == 0 ]; then
    checkSuccess "Requirements validation"
  else
    checkError "Requirements validation"
  fi
}
